import os
import json
from pathlib import Path
from typing import List

# --- LangChain & Pydantic Imports ---
from pydantic import BaseModel, Field
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.exceptions import OutputParserException

def _load_groq_api_key() -> str:
    """Load GROQ_API_KEY from environment or local .env file."""
    env_key = os.environ.get("GROQ_API_KEY")
    if env_key:
        return env_key.strip()
    
    # Fallback to looking in a .env file
    env_file = Path(__file__).resolve().parent / ".env"
    if env_file.exists():
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                if line.startswith("GROQ_API_KEY="):
                    return line.split("=", 1)[1].strip().strip('"\'')
    return ""

# --- Pydantic Schemas for Strict Output Parsing ---
class Edge(BaseModel):
    source: str = Field(description="The exact file path of the file making the import/dependency.")
    target: str = Field(description="The exact file path of the file being imported/depended upon.")

class DependencyGraphEdges(BaseModel):
    edges: List[Edge] = Field(description="List of all internal file dependencies.")

def build_dependency_graph(repo_id: str, data_dir: str = "./Repo_Codes_data") -> str:
    """
    Takes the flat nodes JSON generated by Groq (Pass 1), feeds it to Groq via LangChain,
    and maps the internal edges to create a complete dependency graph.
    """
    api_key = _load_groq_api_key()
    if not api_key:
        raise ValueError("[ERROR] Groq API key is missing. Check your .env file.")

    # 1. Setup paths based on the repo_id
    input_nodes_path = Path(data_dir) / f"{repo_id}.json"
    output_graph_path = Path(data_dir) / f"{repo_id}_graph.json"

    if not input_nodes_path.exists():
        raise FileNotFoundError(f"[ERROR] Nodes file not found at: {input_nodes_path}. Did Pass 1 finish?")

    # 2. Load the flat nodes generated by Pass 1
    with open(input_nodes_path, 'r', encoding='utf-8') as f:
        nodes_data = json.load(f)

    # Extract just the keys (file paths) so we can enforce strict rules on Groq
    valid_file_paths = list(nodes_data.keys())

    # 3. Initialize LangChain Components
    llm = ChatGroq(
        model_name="llama-3.3-70b-versatile",
        temperature=0.1,  # Low temperature for analytical consistency
        groq_api_key=api_key,
        max_retries=2
    )

    parser = JsonOutputParser(pydantic_object=DependencyGraphEdges)

    prompt_template = PromptTemplate(
        template="""
        You are an expert software architect building a dependency graph. 
        I am providing you with a JSON dictionary representing all the files in a code repository. 
        The keys are the relative file paths. The values are metadata about each file, including its "purpose" and a "libraries_used" array.

        Your task: Analyze this data and deduce the internal dependency graph (the edges). 
        If File A imports, requires, or logically depends on File B to function, create an edge where File A is the "source" and File B is the "target".
        
        STRICT RULES:
        1. Both "source" and "target" MUST perfectly match one of the valid file paths listed below. 
        2. Do NOT create edges to external libraries (like React, Pandas, os, etc.). Only create edges between internal repo files.
        3. Analyze the "libraries_used", "purpose", and the file names to deduce these connections.
        
        Valid File Paths (You may only use these exact strings):
        {valid_file_paths}

        Repository Nodes Data:
        {nodes_data}

        CRITICAL INSTRUCTION: Output ONLY valid JSON. Do not include markdown code blocks (like ```json) or any conversational text.
        
        {format_instructions}
        """,
        input_variables=["valid_file_paths", "nodes_data"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )

    # Create the LCEL (LangChain Expression Language) Chain
    chain = prompt_template | llm | parser

    print(f"\n[PASS 2] Groq (via LangChain) is analyzing {len(valid_file_paths)} files to map global dependencies for {repo_id}...")
    
    try:
        # 4. Invoke the LangChain pipeline
        edges_data = chain.invoke({
            "valid_file_paths": json.dumps(valid_file_paths),
            "nodes_data": json.dumps(nodes_data)
        })
        
        edges = edges_data.get("edges", [])
        
        # 5. Combine the original nodes and the new edges into the final graph format
        final_graph = {
            "nodes": nodes_data,
            "edges": edges
        }

        # 6. Save the final output
        with open(output_graph_path, 'w', encoding='utf-8') as f:
            json.dump(final_graph, f, indent=4)
            
        print(f"[SUCCESS] Groq mapped {len(edges)} internal edges.")
        print(f"[SUCCESS] Complete dependency graph saved to: {output_graph_path}")
        
        return str(output_graph_path)

    except OutputParserException as e:
        print(f"[GROQ ERROR] LangChain failed to parse JSON from Groq response: {e}")
        raise
    except Exception as e:
        print(f"[GROQ ERROR] LangChain API request failed: {e}")
        raise

if __name__ == "__main__":
    # Test block
    # Ensure you have a valid {dummy_repo_id}.json generated by repo_tree.py in your ./Repo_Codes_data folder before running this.
    dummy_repo_id = "test_repo" # Replace with an actual ID from your data folder to test standalone
    try:
        build_dependency_graph(dummy_repo_id)
    except Exception as e:
        print(f"Test failed: {e}")